version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_CONNECTION=postgres://postgres:password@postgres/books
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
    volumes:
      - mydata:/var/lib/postgresql/data
volumes:
  mydata:
