apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.postgresql.persistence.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  storageClassName: standard
