name: Test go program
on:
  push:
    branches:
      - '*'

jobs:
  format-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v4.0.0
    - name: format
      run: go fmt
    - name: Git Commit/Push Changes
      uses: actions-x/commit@v6
    - name: Go Test Action
      # You may pin to the exact commit or the version.
      # uses: robherley/go-test-action@d2be031ae805ef1cfd282b685ff38f8b65e799b8
      uses: robherley/go-test-action@v0.1.0
